### DISCUSSION TITLE
grid only shown in devicelist but not on Venus OS overview

### DISCUSSION THREAD

**Discussion by Erkessolar** [freakent/dbus-mqtt-devices#134] [Q&A] [answered]
Hi,

I have installed dbus-mqtt-devices 0.8.0 successfully, emulating a gridmeter.
However the "My Grid Meter" is shown with correct values on the devicelist but not on the overview
Is there a solution available for this issue?
![Devices](https://github.com/user-attachments/assets/4248f052-9581-40b6-b1df-830013f9d22c)
![overview](https://github.com/user-attachments/assets/aa28f9ce-b5ae-4ac8-bd60-480188828971)

**Comment by Candymirror** [comment]
Did you find a solution to this problem? I'm facing the exact same issue.

**Comment by freakent** [comment]
This is not something I have much experience with. The grid meter config was community provided. 

Firstly, are you sure it should appear on the overview screen? The overview screen is fairly limited, especially in guiv1. Have you also tried it in guiv2?

Have you got an example of a gridmeter that does appear on the overview screen?

**Comment by freakent** [comment]
I've just looked at the config in the services.yml file. 

https://github.com/victronenergy/venus/wiki/dbus#grid-and-acload-and-genset-meter

There are three different paths available. I wonder if com.victronenergy.grid or com.victronenergy.acload would give you what you are looking for.

**Comment by Candymirror** [comment]
I'm also quit new to this. Just installed a multiplus 2 and venusOS on a raspberry pi. I was under the impression that the ESS function wasn't correctly working while not showing up on the overview. Eventually I ended up using "https://github.com/mr-manuel/venus-os_dbus-mqtt-grid". With his code it ends up showing on the overview in both gui-v1 and gui-v2. Strangely It stops working as soon as I send a birth message for "services": {"pv1": "pvinverter"} using this implementation. Though showing up under devices.

This is the screenshot using mr-manuel's code
![Schermafdruk van 2025-06-08 11-09-18](https://github.com/user-attachments/assets/0a2162de-f698-4d69-b048-9ecbb83a28e1)

**Reply by freakent** [reply]
Please clarify what I am seeing in the screenshot. Is Net the Grid figure you are expecting?

If you ssh into your Pi, can run a Victron utility called "dbus-spy". You can then see exactly what values have been posted to the dbus.

**Reply by Candymirror** [reply]
Yes. Net is the grid figure I expect to see. And "Zon opbrengst" the vallue for actual PV power from my solar inverter.


dbus-spy output, while using mr-manuel's code:
com.victronenergy.adc                                                        com.victronenergy.fronius
com.victronenergy.grid.mqtt_grid_100                                MQTT Gridcom.victronenergy.hub4
com.victronenergy.logger
com.victronenergy.modbusclient.tcp
com.victronenergy.modbustcp
com.victronenergy.packageManager                              Package Managercom.victronenergy.platform                                              Venuscom.victronenergy.pvinverter.mqtt_pv_102                            MQTT PV 2com.victronenergy.settings
com.victronenergy.system
com.victronenergy.temperature.RpiCpu06                           Raspberry Picom.victronenergy.vebus.ttyUSB0                    MultiPlus-II 48/5000/70-50

**Reply by freakent** [reply]
I guess this is the device you need to look at:

com.victronenergy.grid.mqtt_grid_100 MQTT Grid

Cursor down to it, then press enter.

**Reply by Candymirror** [reply]
Oops, thought of it as if it was a top like program.

Here's the output of "com.victronenergy.grid.mqtt_grid_100" (using mr-manuel's code)
Ac/Current -9.33
Ac/Energy/Forward -
Ac/Energy/Reverse -
Ac/L1/Current -9.33
Ac/L1/Energy/Forward 0
Ac/L1/Energy/Reverse 0
Ac/L1/Frequency -
Ac/L1/Power -2147
Ac/L1/PowerFactor -
Ac/L1/Voltage 230
Ac/Power -2147
Ac/Voltage 230
Connected 1
CustomName MQTT Grid
DeviceInstance 100
FirmwareVersion 0.1.8 (20250331)
Latency -
Mgmt/Connection MQTT Grid service
Mgmt/ProcessName /data/etc/dbus-mqtt-grid/dbus-mqtt-grid.py
Mgmt/ProcessVersion Unkown version, and running on Python 3.8.18
ProductId 65535
ProductName MQTT Grid
UpdateIndex 24 

Here's the output for "com.victronenergy.grid.mqtt_dsmr1_meter1" (using this code, made sure both codes weren't running at the same time):
Ac/Current -8.2
Ac/Energy/Forward -
Ac/Energy/Reverse -
Ac/L1/Current -8.2
Ac/L1/Energy/Forward -
Ac/L1/Energy/Reverse -
Ac/L1/Power -1886
Ac/L1/Voltage 230
Ac/L2/Current -
Ac/L2/Energy/Forward -
Ac/L2/Energy/Reverse -
Ac/L2/Power -
Ac/L2/Voltage -
Ac/L3/Current -
Ac/L3/Energy/Forward -
Ac/L3/Energy/Reverse -
Ac/L3/Power -
Ac/L3/Voltage -
Ac/Power -1886
Connected 1
CustomName My Grid Meter
DeviceInstance 1
DeviceName dsmr1:meter1
DeviceType 0
ErrorCode 0
FirmwareVersion v1.0.0
Mgmt/Connection MQTT:dsmr1
Mgmt/ProcessName dbus-mqtt-devices
Mgmt/ProcessVersion 0.8.0

**Comment by freakent** [comment]
Interesting, many thanks for doing this comparison.  The only significant differences I can see are :
1)  Ac/Voltage  
Ac/Voltage and Ac/Current are deprecated according to Victron's documentation. So it really shouldn't matter but I have see other examples where the classic UI is still using the deprecated attribute.
You could try adding this to your services.yml and restarting dbus-mqt-devices

2) DeviceType
My suspicion is this could be the problem. Victron's documentation does not provide allowed values for this attribute.  Mr Manuel is missing out that attribute altogether.
From dbus-spy you could try setting it to a few different values. (just press Enter while on the DeviceType line and you can manualy set a value). Or you could try removing that attribue from services.yml altogether and restarting dbus-mqtt-devices.

```
# https://github.com/victronenergy/venus/wiki/dbus#grid-and-genset-meter
grid:
  ProductId:
    default: 65535 # 0xFFFF
  CustomName:
    default: "My Grid Meter"
    persist: true
  ErrorCode: # https://www.victronenergy.com/live/mppt-error-codes
    description: "0=No Error"
    default: 0
  Ac/Energy/Forward: # Total bought energy over all phases
    description: "kWh"
    format: "{} kWh"
  Ac/Energy/Reverse: # Total sold energy over all phases
    description: "kWh"
    format: "{} kWh"
  Ac/Power: # Total power of all phases, preferably real power
    description: "W"
    format: "{} W"
  Ac/Current:
    description: "A AC"
    format: "{} A"
  Ac/Voltage:
    description: "V AC"
    format: "{} V"
  Ac/L1/Current:
    description: "A AC"
    format: "{} A"
  Ac/L1/Energy/Forward:
    description: "kWh"
    format: "{} kWh"
  Ac/L1/Energy/Reverse:
    description: "kWh"
    format: "{} kWh"
  Ac/L1/Power:
    description: "W"
    format: "{} W"
  Ac/L1/Voltage:
    description: "V AC"
    format: "{} V"
  Ac/L2/Current:
    description: "A AC"
    format: "{} A"
  Ac/L2/Energy/Forward:
    description: "kWh"
    format: "{} kWh"
  Ac/L2/Energy/Reverse:
    description: "kWh"
    format: "{} kWh"
  Ac/L2/Power:
    description: "W"
    format: "{} W"
  Ac/L2/Voltage:
    description: "V AC"
    format: "{} V"
  Ac/L3/Current:
    description: "A AC"
    format: "{} A"
  Ac/L3/Energy/Forward:
    description: "kWh"
    format: "{} kWh"
  Ac/L3/Energy/Reverse:
    description: "kWh"
    format: "{} kWh"
  Ac/L3/Power:
    description: "W"
    format: "{} W"
  Ac/L3/Voltage:
    description: "V AC"
    format: "{} V"
```

**Comment by freakent** [comment]
Looking at Mr Manual's code, he has set the DeviceTyoe as follows. I don't understand why we don't see this in dbus-spy.
```
; Device type
; grid = Grid
; genset = Generator
; acload = AC Load (does not impact calculations, shows only under devices)
device_type = grid
```
So maybe grid is the correct value for DeviceType. 

The definition of DeviceType is services.yml would look like this:
```
  DeviceType: 
    description: "grid, genset or acload "
    persist: true
    default: grid
```

**Comment by Candymirror** [comment]
AC/Voltage and AC/Current weren't provided by me previous. I've added these values to check if these would make a difference.
Using:
```   
DeviceType: 
    description: "grid, genset or acload "
    persist: true
    default: grid
```

Doesn't change the behavior.

BTW running both instances together (yours and mr-manuel) will display empty (--)  value for grid as soon as the "birth" message is sent:
`{"clientId": "dsmr1", "connected": 1, "version": "v1.0.0", "services": {"meter1": "grid"} }` to topic: `device/dsmr1/Status`

Things actually take a turn for worse as soon as soon as the first value is published in the topic. Then the dashboard stops for grid, pv and battery
