### DISCUSSION TITLE
Alternator or DC/DC Charger Emulations?

### DISCUSSION THREAD

**Discussion by pbawesome** [freakent/dbus-mqtt-devices#140] [Ideas]
I'd like to integrate Wakespeed stuff beyond their integrations. Their DC/DC Charger currently doesn't have an integration, but I know it exists on the Victron side. 

What I am trying to do is respresent the output of their DC/DC Charger into victron as "alternator charging" it is a 3000W DC/DC Charger.

I will work on how to get that data whether it be through dbus, nmea2000 over can, or even usb serial, or even a victron smartshunt, but I want it to show up as alternator charging in VRM

**Comment by freakent** [comment]
Sorry this is not something this driver currently supports. That's not to say it's something that couldn't be done but I don't have the hardware or any way of emulating the hardware.

**Reply by pbawesome** [reply]
I have the hardware. Where are you located? I would be happy to contribute to your project if provided with some guidance. I've been familiarizing myself with your code today. At the present moment I am only using the temperature and GPS portions and it works fantastic!

**Reply by freakent** [reply]
I'm based in the UK. 

To get started with this we need to identify which Victron Dbus service this needs to identify as.  The full list is here. 

https://github.com/victronenergy/venus/wiki/dbus

I have Victron Orion TR DC-DC chargers in my set up. They appear in the dbus as com.victronenergy.alternator (https://github.com/victronenergy/venus/wiki/dbus#alternator-and-dcsource)

The only way to know for sure which is best is to set up the required attributes in the service.yml config file and then create a mock up test script that registers itself and sends some dummy data to the appropriate attributes. Then check in the Venus OS UI to see if those dummy data values are being displayed as required.

**Comment by pbawesome** [comment]
It would be these two
https://github.com/victronenergy/venus/wiki/dbus#dcdc-converters
https://github.com/victronenergy/venus/wiki/dbus#alternator-and-dcsource

They already have specific wakespeed fields
<img width="410" alt="image" src="https://github.com/user-attachments/assets/6d554b68-193b-4997-97d8-8040e2854e39" />
Currently the engine is off so I'm not getting any useful data. I need to go turn the engine on and see if I can get any useful data out of there.

I do not have a victron dc/dc so I can't see what that would have in there. But I guess now I need to figure out how to create an "alternator" device

**Comment by pbawesome** [comment]
<img width="756" alt="image" src="https://github.com/user-attachments/assets/cfe434a1-602a-4f98-81b4-5f895ae19ff6" />
I guess the question is how do I register an alternator device like this and publish to it?

**Reply by freakent** [reply]
Let me have a first crack at creative some config for the settings.yaml file.

**Reply by pbawesome** [reply]
Thank you, I found it but you are the expert here. Do you need to re-run the setup after modifying that file? or does this drivers service reference the /data/drivers directory?
root@einstein:/data# sudo find /data -name services.yml 2>/dev/null
/data/drivers/dbus-mqtt-devices-0.8.0/services.yml

**Reply by freakent** [reply]
No you shouldn't run setup.sh again,but you do need to restart the service or simply reboot the GX device.

**Reply by freakent** [reply]
You can try appending the following to the bottom of you service.yml. Be very careful with formatting as the right indentation is very important. After rebooting follow the instruction on the readme on monitoring the log file. 

**But before you do that, lets discuss it these attributes actually make sense in your use case and  whether you would be able to provide values for each.**

```
# https://github.com/victronenergy/venus/wiki/dbus#alternator-and-dcsource
alternator:
  ProductId:
    default: 65535 # 0xFFFF
  CustomName:
    default: "My Alternator"
    persist: true
  Dc/0/Voltage:
    description: "V DC"
  Dc/0/Current:
    description: "A, positive when alternator is charging"
  Dc/0/Temperature:
    description: "Degrees centigrade, alternator temperature reading, or temperature sensor on SmarShunt/BMV (not available for OrionXS)"
  Dc/1/Voltage:
    description: "SmartShunt/BMV secondary battery voltage (if configured)"
  Engine/Speed:
    description: "Engine RPN (or should that be RPM?)"
  FieldDrive:
    description: "Current limit in %"
  Speed:
    description: "Alternator RPM"
  State:
    description: "0=Off, 2=Fault, 3=Bulk, 4=Absorption, 5=Float, 6=Storage, 7=Equalize, 252=External control"
```
