### DISCUSSION TITLE
Integration of heatpump as a separate service?

### DISCUSSION THREAD

**Discussion by BeneWilh** [freakent/dbus-mqtt-devices#142] [General]
Hi @freakent, thank you for sharing your scrpts for venus os. Would you be able and willing to add some additional devices such as heatpump in your scripts?

For the time beeing I am using a third EVCharger to show the values on VRM... but as values are summed up its not that nice.
Thank you!

**Comment by freakent** [comment]
Hi,

I'm always happy to discuss and  to investigate feasibility. In this case the config for Heat Pumps looks relatively straignt forward.
https://github.com/victronenergy/venus/wiki/dbus#heatpump

As usual it comes down to  what 3rd party device you are trying to integrate and whether the data it provides maps  to what Victron supports in their dbus interface (see the link above). 

You could try adding the following lines to your services.yml file, reboot, then try publishing over mqtt a registration message for a heat pump device.   Check the dbus-mqtt-devices log file as per the troubleshooting instructions in the README.  If it registers OK, then try sending some data attriibutes using the device id.
 
```
# hhttps://github.com/victronenergy/venus/wiki/dbus#heatpump
heatpump:
  ProductId:
    default: 65535 # 0xFFFF
  CustomName:
    default: "My Heat Pump"
    persist: true
  State:
    description: "State of heat pump (enum to be decided later)"
  Temperature:
    description: "Current water temperature (optional if no temperature reading available)"
  TargetTemperature:
    description: "Target water temperature (optional if not available)"
  Ac/Power:
    description: "Power currently consumed"
  Ac/Energy/Forward:
    description: "Total energy consumed"

```

I am having to guess the the dbus identifier for this is com.victronenergy.**heatpump**, as Victron have not included it in their documentation.
