### ISSUE TITLE
Adopt services.yml for pvinverters

### ISSUE THREAD

**Issue by stromibaer** [freakent/dbus-mqtt-devices#23]
Pls add following lines and/or adopt some lines in the pvinverter section:

![image](https://user-images.githubusercontent.com/47776842/197048506-2bc382f0-1dbf-4e55-8618-59eeca2eac03.png)

to:

 ```
 AllowedRoles:
    default: ["grid", "pvinverter", "genset", "acload"]
  Role:
    description: "grid, pvinverter, genset, acload"
    persist: true
    default: "pvinverter"
```

The default line in AllowedRoles has some format issues with ''.

And adopt the comment field:

![image](https://user-images.githubusercontent.com/47776842/197049082-f4561d25-a586-4aa3-af98-55ea01ce0137.png)

to:

 ```
 ProductId:
    default: 45069 # 45069 ET340, 45068 ET112 - 0xB00D, ESS Demo mode uses 45058
```

ET340 is for 3 phases and ET112 is for one phase metering.

With this changes it is possible to change default location of the inverter from AC-OUT to AC-IN or vice versa in the Cerbo settings menue.

Thanks,
Peter
