### ISSUE TITLE
Request for support com.victronenergy.solarcharger

### ISSUE THREAD

**Issue by pos-ei-don** [freakent/dbus-mqtt-devices#31]
I am currently trying to add a solarcharger,
to feed in data from an additional power-source (a balkony system
where i measure the power with tasmota in mqtt).
My goal is to change the mqtt-Data from Tasmota via Nodered to be compatible to this
driver so i can see the data in the vrm plots and graphs.

My current work in Progress is below.
I see the device popping up and showing some numbers, but it stays in not activ status.
Can someone help me where  i might have an error?
Has someone a working example? I tried to stay basic, then i added addidional values.
If I add the commented out  # ErrorCode, it does not show up at all. Why?

best regards, Joe

```
solarcharger:
  ProductId:
    default: 41074 # 
  CustomName:
    default: "Solarcharger"
    persist: true
  NrOfTrackers:
    description: "Trackers"
    default: 1
  Pv/P: # 
    description: "W"
    persist: true
    default: 0
    format: "{} W"
  Pv/0/P: # 
    description: "W"
    persist: true
    default: 0
    format: "{} W"
  Pv/0/V: #
    description: "V"
    default: 0
    format: "{} V"
  Pv/V: # DD
    description: "V"
    default: 0
    format: "{} V"
  Dc/0/Current: # DD
    description: "A"
    default: 0
    format: "{} A"
  Dc/0/Voltage: # DD
    description: "V"
    default: 52
    format: "{} V"
  Yield/Power: #
    description: "W"
    default: 0
    format: "{} W"
  Yield/SYSTEM: #
    description: "W"
    default: 0
    format: "{} W"
  Yield/User: #
  Link/NetworkStatus:
    description: ""
    default: 4 # 0x8
  Link/NetworkMode:
    description: ""
    default: 13 # 0x8
  Link/ChargeCurrent:
    description: ""
    default: 20 # 0x8
#  ErrorCode
#    description: "0=No Error"
#    default: 0 # not showing in in console???
#  Connected:
#    description: ""
#    default: 1 #
  Mode:
    description: ""
    default: 1 #
  MppOperationMode:
    description: ""
    default: 2 #
```
