### ISSUE TITLE
Add AC Load energy meter

### ISSUE THREAD

**Issue by Woodpeckercz** [freakent/dbus-mqtt-devices#66]
Hi,

Would it be possible to add a AC load energy meter to the services? I would like to add my immersion heater as separate load to the vrm because I have a solar diverter installed. When the battery is full, the excess solar goes to hot water, and I would like to see how much energy went in.

**Comment by Woodpeckercz** [comment]
So I noticed there is a config for the PV inverter that allows it to be set to AC load but is comented out.
How would I go about enabling this?
```
# https://github.com/victronenergy/venus/wiki/dbus#pv-inverters
pvinverter:
  ProductId:
    default: 45069 # 0xB00D, ESS Demo mode uses 45058
  CustomName:
    default: "My PV Inverter"
    persist: true
  ErrorCode: # https://www.victronenergy.com/live/mppt-error-codes
    description: "0=No Error"
    default: 0 # not showing in in console???
  Position:
    description: "0=AC input 1; 1=AC output; 2=AC input 2"
    persist: true
    default: 0
    min: 0
    max: 2
  StatusCode: # not used by ESS demo mode pvinverter
    description: "0=Startup 0; 1=Startup 1; 2=Startup 2; 3=Startup 3; 4=Startup 4; 5=Startup 5; 6=Startup 6; 7=Running; 8=Standby; 9=Boot loading; 10=Error"
    default: 7
    min: 0
    max: 10
#  AllowedRoles:
#    default: '["grid", "pvinverter", "genset", "acload"]'
#  Role:
#    description: "grid, pvinverter, genset, acload"    
#    persist: true
#    default: "pvinverter"
```
