### ISSUE TITLE
Add Status attribute for Temperature dbus path

### ISSUE THREAD

**Issue by freakent** [freakent/dbus-mqtt-devices#87]
As per discussion #80 started by @gharsaw.

**Comment by freakent** [comment]
Temperature devices in Demo mode include this attribute so make sense to add it to the services config.  Same applies to Tanks. Doesn't appear to be affecting display in either of the new guis at this time.

/Status             0=Ok; 1=Disconnected; 2=Short circuited; 3=Reverse polarity; 4=Unknown

```
Status:
  description: "0=Ok, 1=Disconnected, 2=Short circuited, 3=Reverse polarity, 4=Unknown"
  persist: false
  default: 0
  min: 0
  max: 4
```
